.TH "quickcurver" 1 "02 May 2022" "redacted@redacted.com" "quickcurver Documentation"

.SH NAME
quickcurver \- A Curve Fever implementation in Qt

.SH SYNOPSIS
.B quickcurver
[\-h]

.SH DESCRIPTION

.P
This is an implementation of Curve Fever (also known as Achtung die Kurve) in Qt.

.TP
.B \-h
Show usage information.

.SH EXIT STATUS
Returns zero on success.

.SH NOTES
The quickcurver project site, with more information and the source code repository, can be found at https://github.com/vimpostor/quickcurver. This program is currently under development, please report any bugs at the project site or directly to the author.
